[project]
name = "python-django-development-project-52"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "dj-database-url>=3.0.1",
    "django>=6.0",
    "gunicorn>=23.0.0",
    "psycopg2-binary>=2.9.11",
]
